PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000001_create_departments_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000002_create_positions_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000003_create_users_table',1);
INSERT INTO migrations VALUES(4,'0001_01_01_000004_create_cache_table',1);
INSERT INTO migrations VALUES(5,'0001_01_01_000005_create_jobs_table',1);
INSERT INTO migrations VALUES(6,'2024_06_14_234956_add_two_factor_columns_to_users_table',1);
INSERT INTO migrations VALUES(7,'2025_01_04_202301_create_categories_table',1);
INSERT INTO migrations VALUES(8,'2025_01_04_202302_create_subcategories_table',1);
INSERT INTO migrations VALUES(9,'2025_01_04_202322_create_people_table',1);
INSERT INTO migrations VALUES(10,'2025_01_04_202334_create_services_table',1);
INSERT INTO migrations VALUES(11,'2025_02_02_172353_create_groups_table',1);
INSERT INTO migrations VALUES(12,'2025_02_02_200943_create_campaigns_table',1);
INSERT INTO migrations VALUES(13,'2025_02_03_204305_create_campaign_group_table',1);
INSERT INTO migrations VALUES(14,'2025_02_04_103105_alteruseridnullableinservicestable',1);
INSERT INTO migrations VALUES(15,'2025_02_10_202249_create_configurations_table',1);
INSERT INTO migrations VALUES(16,'2025_03_03_101227_add_to_campaigns_schedule',1);
INSERT INTO migrations VALUES(17,'2025_03_03_150418_add_count_columns_to_campaigns_table',1);
INSERT INTO migrations VALUES(18,'2025_03_03_151101_add_missing_columns_to_campaigns_table',1);
INSERT INTO migrations VALUES(19,'2025_03_25_084428_create_orders_table',1);
INSERT INTO migrations VALUES(20,'2025_04_03_104631_create_historics_table',1);
INSERT INTO migrations VALUES(21,'2025_04_07_185106_add_cnpj_department_table',1);
INSERT INTO migrations VALUES(22,'2025_04_21_091836_add_status_to_services',1);
INSERT INTO migrations VALUES(23,'2025_04_21_095116_add_department_to_services',1);
INSERT INTO migrations VALUES(24,'2025_04_28_193047_add_address_to_order',1);
INSERT INTO migrations VALUES(25,'2025_05_12_093712_add_webhook_check_to_departments',1);
INSERT INTO migrations VALUES(26,'2025_05_13_110111_create_nps_table',1);
INSERT INTO migrations VALUES(27,'2025_05_13_111059_create_nps_responses_table',1);
CREATE TABLE IF NOT EXISTS "departments" ("id" integer primary key autoincrement not null, "nome" varchar not null, "logo" varchar, "email" varchar, "telefone_principal" varchar, "telefone_secundario" varchar, "rua" varchar, "numero" varchar, "bairro" varchar, "cidade" varchar, "cep" varchar, "uf" varchar, "complemento" varchar, "created_at" datetime, "updated_at" datetime, "cnpj" varchar, "send_message" tinyint(1) not null default '0', "webhook_n8n_service" varchar, "webhook_n8n_order" varchar, "webhook_n8n_campaign" varchar);
INSERT INTO departments VALUES(1,'Secretaria De Saúde','https://via.placeholder.com/640x480.png/000088?text=business+necessitatibus','secretaria@housecriative.com.br','(11) 99999-9999',NULL,'','68','Et','',NULL,'RJ','F','2024-08-05 16:13:13','2025-05-14 11:26:03','12.345.678/9012-34',1,'https://n8n-main.gestaohouse.com.br/webhook-test/create-service-saude','https://n8n-main.gestaohouse.com.br/webhook-test/status-change-order-saude','https://n8n-main.gestaohouse.com.br/webhook-test/send-campaign-saude');
CREATE TABLE IF NOT EXISTS "positions" ("id" integer primary key autoincrement not null, "nome" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "nivel" varchar not null default 'padrao', "whatsapp" varchar, "is_ativo" tinyint(1) not null default '0', "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "position_id" integer, "departamento_id" integer, "two_factor_secret" text, "two_factor_recovery_codes" text, foreign key("position_id") references "positions"("id"), foreign key("departamento_id") references "departments"("id"));
INSERT INTO users VALUES(1,'Roberto Ferreira','SuperAdmin',NULL,1,'roberto@housecriative.com.br','2025-05-14 11:12:20','$2y$12$ky655b4qCZdYIy1BkA9Cf.jwFgxeFY8VikTpYcHysUOsJEfqgBAxe','iFolvKBX4P','2025-05-14 11:12:20','2025-05-14 11:12:20',NULL,NULL,NULL,NULL);
INSERT INTO users VALUES(2,'Ferreira Júnior','SuperAdmin',NULL,1,'paulojunior@housecriative.com.br','2025-05-14 11:12:20','$2y$12$ky655b4qCZdYIy1BkA9Cf.jwFgxeFY8VikTpYcHysUOsJEfqgBAxe','UEMvCiHe0m','2025-05-14 11:12:20','2025-05-14 11:12:20',NULL,NULL,NULL,NULL);
INSERT INTO users VALUES(3,'Arthur Vinícius','SuperAdmin',NULL,1,'arthurvinice@gmail.com','2025-05-14 11:12:20','$2y$12$ky655b4qCZdYIy1BkA9Cf.jwFgxeFY8VikTpYcHysUOsJEfqgBAxe','Gzk56hdlqf','2025-05-14 11:12:20','2025-05-14 11:12:20',NULL,NULL,NULL,NULL);
INSERT INTO users VALUES(4,'Ilana Martins','Administrador',NULL,1,'adm-saude@gmail.com','2025-05-14 11:12:20','$2y$12$ky655b4qCZdYIy1BkA9Cf.jwFgxeFY8VikTpYcHysUOsJEfqgBAxe','EFE9HKPxhh','2025-05-14 11:12:20','2025-05-14 11:12:20',NULL,1,NULL,NULL);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "sessions" ("id" varchar not null, "user_id" integer, "ip_address" varchar, "user_agent" text, "payload" text not null, "last_activity" integer not null, primary key ("id"));
INSERT INTO sessions VALUES('PMcPzYYTTAQXfL9dUdNWeaASDd5rt3cNsGcxD1PK',4,'127.0.0.1','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36','YTo1OntzOjY6Il90b2tlbiI7czo0MDoiSEkzTFFIdllBWkdSckgxVUljVkdEUlB3UXRGZ213RVVURnZ0czk3UyI7czozOiJ1cmwiO2E6MDp7fXM6OToiX3ByZXZpb3VzIjthOjE6e3M6MzoidXJsIjtzOjM5OiJodHRwOi8vbG9jYWxob3N0OjgwMDAvYWRtaW4vY2FtcGFpZ25zLzEiO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX1zOjUwOiJsb2dpbl93ZWJfNTliYTM2YWRkYzJiMmY5NDAxNTgwZjAxNGM3ZjU4ZWE0ZTMwOTg5ZCI7aTo0O30=',1747308974);
INSERT INTO sessions VALUES('DXXM4epDtH2NsfAtQJpsD4zJBssrhChu3QAfeiQK',4,'10.0.3.27','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36','YTo0OntzOjY6Il90b2tlbiI7czo0MDoiRXRWa1Fwb29tR3FkM0RzYUVWbEhsaHVYYVJ6ZHJmTnhydVhzbmU3RCI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6Mzk6Imh0dHA6Ly8xMC4wLjMuMjc6ODAwMC9hZG1pbi9jYW1wYWlnbnMvMSI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjQ7fQ==',1747311571);
INSERT INTO sessions VALUES('GEjVvFTSo0x7cZGRbP2cN0PDbE3xiwB2nP9W1jHQ',NULL,'10.0.3.27','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36','YTozOntzOjY6Il90b2tlbiI7czo0MDoia3FLUTdkYjlFdjhJRnd3YXdYc3BXSXhXMTlhTFczU2dXbWNLbnpzdCI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MzQ6Imh0dHA6Ly8xMC4wLjMuMjc6ODAwMC9ucHMvc2VuZC1ucHMiO31zOjY6Il9mbGFzaCI7YToyOntzOjM6Im9sZCI7YTowOnt9czozOiJuZXciO2E6MDp7fX19',1747319052);
INSERT INTO sessions VALUES('MaS9qZIw01TNXlAY92CQ9OWw5HTnHdT88YR4E7I0',NULL,'127.0.0.1','PostmanRuntime/7.39.1','YToyOntzOjY6Il90b2tlbiI7czo0MDoiVmpvYjFlYnRscWR6WnpLVlpoZ2FERVYzU0p5MmhvWlE2OG5lamZEWSI7czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319fQ==',1747319360);
INSERT INTO sessions VALUES('rGJyBdrnYJDYXkEqeBHEalCr6VtvqMnLwJ1GpzjG',4,'127.0.0.1','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36','YTo1OntzOjY6Il90b2tlbiI7czo0MDoicUlBcW1oWndrekpoSkI4eFRZcVFMYzZtd1JLc2U1NXJKVVFNek01ZiI7czo5OiJfcHJldmlvdXMiO2E6MTp7czozOiJ1cmwiO3M6MzU6Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMC9ucHMvdGVzdC1mb3JtIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo1MDoibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO2k6NDtzOjIyOiJQSFBERUJVR0JBUl9TVEFDS19EQVRBIjthOjA6e319',1747321078);
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
INSERT INTO cache VALUES('9ad73ac120d5e9abaa3f8c33b3b3b236:timer','i:1747309580;',1747309580);
INSERT INTO cache VALUES('9ad73ac120d5e9abaa3f8c33b3b3b236','i:1;',1747309580);
INSERT INTO cache VALUES('ed77c0d29021b5ccdae70e98f6f90159:timer','i:1747319954;',1747319954);
INSERT INTO cache VALUES('ed77c0d29021b5ccdae70e98f6f90159','i:1;',1747319954);
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "categories" ("id" integer primary key autoincrement not null, "titulo" varchar not null, "departamento_id" integer not null, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "subcategories" ("id" integer primary key autoincrement not null, "titulo" varchar not null, "categoria_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("categoria_id") references "categories"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "people" ("id" integer primary key autoincrement not null, "nome" varchar not null, "apelido" varchar, "cpf" varchar not null, "whatsapp" varchar, "genero" varchar, "escolaridade" varchar, "data_nascimento" date, "rua" varchar, "numero" varchar, "bairro" varchar, "cidade" varchar, "cep" varchar, "uf" varchar, "latitude" numeric, "longitude" numeric, "geocoded_at" datetime, "complemento" varchar, "created_at" datetime, "updated_at" datetime);
INSERT INTO people VALUES(1,'Roberto Ferreira','fabricio75','12345678900','8498189508',NULL,NULL,'1990-01-01','Rua das Flores','123','Centro','São Paulo','12345-678','SP',-41.5285310000000009,-18.5278379999999991,NULL,'Quia voluptatem error et perferendis sit.','2025-05-14 11:12:20','2025-05-14 11:12:20');
INSERT INTO people VALUES(2,'Ferreira Júnior','aranda.ziraldo','98765432100','8499210110',NULL,NULL,'1990-01-01','Rua das Flores','123','Centro','São Paulo','12345-678','SP',NULL,-140.639320999999995,NULL,'Quos magnam corrupti totam.','2025-05-14 11:12:20','2025-05-14 11:12:20');
INSERT INTO people VALUES(3,'Arthur Vinícius','zuchoa','12345678910','84996127773',NULL,NULL,'1990-01-01','Rua das Flores','123','Centro','São Paulo','12345-678','SP',-78.7581679999999977,NULL,'1990-08-15 12:00:49','Magni rerum dolorum occaecati delectus vitae aut animi.','2025-05-14 11:12:20','2025-05-14 11:12:20');
CREATE TABLE IF NOT EXISTS "groups" ("id" integer primary key autoincrement not null, "nome" varchar not null, "descricao" text, "created_at" datetime, "updated_at" datetime);
INSERT INTO "groups" VALUES(1,'grupo teste',NULL,'2025-05-14 11:12:55','2025-05-14 11:12:55');
CREATE TABLE IF NOT EXISTS "group_people" ("id" integer primary key autoincrement not null, "group_id" integer not null, "people_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("group_id") references "groups"("id") on delete cascade, foreign key("people_id") references "people"("id") on delete cascade);
INSERT INTO group_people VALUES(1,1,1,NULL,NULL);
INSERT INTO group_people VALUES(2,1,2,NULL,NULL);
INSERT INTO group_people VALUES(3,1,3,NULL,NULL);
CREATE TABLE IF NOT EXISTS "campaigns" ("id" integer primary key autoincrement not null, "name" varchar not null, "message" text not null, "image_url" varchar, "video_url" varchar, "audio_url" varchar, "recipients" text not null, "status" varchar check ("status" in ('pending', 'in_progress', 'completed', 'failed')) not null default 'pending', "created_at" datetime, "updated_at" datetime, "scheduled_at" datetime, "is_scheduled" tinyint(1) not null default '0', "sent_count" integer not null default '0', "fail_count" integer not null default '0', "sent_at" datetime);
INSERT INTO campaigns VALUES(1,'campanha teste','testando',NULL,NULL,NULL,'"[\"+558498189508\",\"+558499210110\",\"+5584996127773\"]"','pending','2025-05-14 11:13:18','2025-05-15 09:18:42',NULL,0,0,0,NULL);
CREATE TABLE IF NOT EXISTS "campaign_group" ("id" integer primary key autoincrement not null, "campaign_id" integer not null, "group_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("campaign_id") references "campaigns"("id") on delete cascade, foreign key("group_id") references "groups"("id") on delete cascade);
INSERT INTO campaign_group VALUES(1,1,1,NULL,NULL);
CREATE TABLE IF NOT EXISTS "configurations" ("id" integer primary key autoincrement not null, "nome_fantasia" varchar, "razao_social" varchar, "cnpj" varchar, "telefone_principal" varchar, "whatsapp" varchar, "email" varchar, "logo" varchar, "avatar" varchar, "rua" varchar, "numero" varchar, "bairro" varchar, "cidade" varchar, "cep" varchar, "estado" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "orders" ("id" integer primary key autoincrement not null, "descricao" text, "status" varchar default 'Em Aberto', "solucao" text, "previsao_solucao" date, "data_transferencia" date, "created_at" datetime, "updated_at" datetime, "categoria_id" integer, "subcategoria_id" integer, "create_user_id" integer, "responsavel_user_id" integer, "pessoa_id" integer, "update_user_id" integer, "dono_setor_id" integer, "antigo_setor_id" integer, "rua" varchar, "numero" varchar, "bairro" varchar, "cidade" varchar, "cep" varchar, "uf" varchar, "complemento" varchar, foreign key("categoria_id") references "categories"("id") on delete cascade, foreign key("subcategoria_id") references "subcategories"("id") on delete cascade, foreign key("create_user_id") references "users"("id") on delete cascade, foreign key("responsavel_user_id") references "users"("id") on delete cascade, foreign key("pessoa_id") references "people"("id") on delete cascade, foreign key("update_user_id") references "users"("id") on delete cascade, foreign key("dono_setor_id") references "departments"("id") on delete cascade, foreign key("antigo_setor_id") references "departments"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "historics" ("id" integer primary key autoincrement not null, "descricao" text not null, "created_at" datetime, "updated_at" datetime, "user_id" integer, "order_id" integer, foreign key("user_id") references "users"("id") on delete cascade, foreign key("order_id") references "orders"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "services" ("id" integer primary key autoincrement not null, "observacao" varchar, "pessoa_id" integer not null, "categoria_id" integer not null, "user_id" integer, "data" datetime, "notas" text, "confirmacao" tinyint(1), "created_at" datetime, "updated_at" datetime, "status" varchar default ('Em Aberto'), "departamento_id" integer, foreign key("user_id") references users("id") on delete cascade on update no action, foreign key("categoria_id") references categories("id") on delete cascade on update no action, foreign key("pessoa_id") references people("id") on delete cascade on update no action, foreign key("departamento_id") references "departments"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "nps" ("id" integer primary key autoincrement not null, "titulo" varchar not null, "texto" text, "departamento_id" integer, "order_id" integer, "service_id" integer, "created_at" datetime, "updated_at" datetime, foreign key("departamento_id") references "departments"("id") on delete cascade, foreign key("order_id") references "orders"("id") on delete cascade, foreign key("service_id") references "services"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "nps_responses" ("id" integer primary key autoincrement not null, "nps_id" integer not null, "rating" integer not null, "whatsapp" varchar, "expired_at" datetime not null default '2025-05-21 11:12:20', "created_at" datetime, "updated_at" datetime, foreign key("nps_id") references "nps"("id") on delete cascade);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',27);
INSERT INTO sqlite_sequence VALUES('services',0);
INSERT INTO sqlite_sequence VALUES('departments',1);
INSERT INTO sqlite_sequence VALUES('users',4);
INSERT INTO sqlite_sequence VALUES('people',3);
INSERT INTO sqlite_sequence VALUES('groups',1);
INSERT INTO sqlite_sequence VALUES('group_people',3);
INSERT INTO sqlite_sequence VALUES('campaigns',1);
INSERT INTO sqlite_sequence VALUES('campaign_group',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "sessions_user_id_index" on "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" on "sessions" ("last_activity");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "people_cpf_unique" on "people" ("cpf");
CREATE INDEX people_nome_index ON people(nome);
CREATE INDEX people_cpf_index ON people(cpf);
CREATE INDEX positions_nome_index ON positions(nome);
COMMIT;
